name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install French locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen fr_FR.UTF-8
          sudo dpkg-reconfigure locales
      
      - name: Replace placeholder with Python
        run: |
          python3 << EOF
          import datetime
          import locale
          try:
            locale.setlocale(locale.LC_TIME, 'fr_FR.UTF-8')
          except locale.Error:
            locale.setlocale(locale.LC_TIME, 'fr_FR')
          locale.setlocale(locale.LC_TIME, 'fr_FR.UTF-8')
          with open('index.html', 'r', encoding='utf-8') as f:
            content = f.read()
          content = content.replace('{{LAST_UPDATED}}', datetime.datetime.now().strftime('%d %B %Y'))
          with open('index.html', 'w', encoding='utf-8') as f:
            f.write(content)
          EOF
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages